"""
Renders an ImpactReport as a formatted GitHub PR comment.
"""

from __future__ import annotations

from models import ImpactReport

_RISK_EMOJI = {"Low": "🟢", "Medium": "🟡", "High": "🔴"}
_TEST_EMOJI = {
    "Smoke Testing": "💨",
    "Functional Testing": "⚙️",
    "Regression Testing": "🔁",
    "Integration Testing": "🔗",
    "API Testing": "📡",
    "Security Testing": "🔒",
    "Performance Testing": "⚡",
}


def render_comment(report: ImpactReport) -> str:
    risk_icon = _RISK_EMOJI.get(report.risk, "⚪")
    confidence_bar = "█" * (report.confidence // 10) + "░" * (10 - report.confidence // 10)

    affected_md = "\n".join(f"- `{c}`" for c in report.affected_components) or "- None identified"
    indirect_md = "\n".join(f"- `{c}`" for c in report.potentially_impacted_components) or "- None identified"
    risk_reasons_md = "\n".join(f"- {r}" for r in report.risk_reasons) or "- N/A"
    testing_md = "\n".join(
        f"- {_TEST_EMOJI.get(t, '🧪')} {t}" for t in report.testing_scope
    ) or "- N/A"
    files_md = "\n".join(f"- `{f}`" for f in report.changed_files)

    return f"""\
## 🤖 AI Impact Analysis

| Field | Value |
|-------|-------|
| **Change Type** | {report.change_type} |
| **Risk** | {risk_icon} {report.risk} |
| **Confidence** | `{confidence_bar}` {report.confidence}% |

### 📦 Directly Affected Components
{affected_md}

### 🔗 Potentially Impacted Components
{indirect_md}

### ⚠️ Risk Reasons
{risk_reasons_md}

### 🧪 Testing Scope
{testing_md}

### 📝 Summary
{report.summary}

### 📁 Changed Files ({len(report.changed_files)})
{files_md}

---
*Generated by G4 AI Impact Agent*"""
